name: "CI"
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.10.0
      - run: pixi run download-cv --token ${{ secrets.GH_RESUME_REPO_PAT }}
      - run: pixi run docs-build
      - uses: actions/upload-artifact@v7
        with:
          name: Website
          path: ./site
          if-no-files-found: error
          retention-days: 3
